"""Export SnakeAI's PyTorch checkpoint to a JS file the browser demo can load.

Reads model/model.pth from https://github.com/Macapps13/SnakeAI (a Linear_QNet
11 -> 256 -> 3) without needing torch installed: a .pth is a zip whose
data/<n> entries are raw little-endian float32 tensors.

Usage:
    python3 tools/export_snake_weights.py path/to/model.pth assets/snake/model.js
"""

import base64
import json
import sys
import zipfile

# Storage index -> (name, shape), in Linear_QNet.state_dict() order.
LAYOUT = [
    ("w1", (256, 11)),
    ("b1", (256,)),
    ("w2", (3, 256)),
    ("b2", (3,)),
]


def main(src, dst):
    with zipfile.ZipFile(src) as z:
        names = z.namelist()
        root = names[0].split("/")[0]
        weights = {}
        for idx, (name, shape) in enumerate(LAYOUT):
            raw = z.read(f"{root}/data/{idx}")
            expected = 4
            for dim in shape:
                expected *= dim
            if len(raw) != expected:
                raise SystemExit(f"{name}: expected {expected} bytes, got {len(raw)}")
            weights[name] = {"shape": list(shape), "data": base64.b64encode(raw).decode()}

    with open(dst, "w") as f:
        f.write("// Generated by tools/export_snake_weights.py from SnakeAI/model/model.pth.\n")
        f.write("// Linear_QNet(11, 256, 3): float32, row-major, base64-encoded.\n")
        f.write(f"window.SNAKE_MODEL = {json.dumps(weights, indent=2)};\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
