#!/usr/bin/env node
// Trains the Snake DQN headlessly with the same engine the browser demo uses,
// keeps the checkpoint with the best greedy evaluation, and writes it in the
// format assets/snake/model.js expects (same as export_snake_weights.py).
//
// Usage: node tools/train_snake.js [games=400] [out=assets/snake/model.js]

const fs = require('fs');
const path = require('path');
const { SnakeGame, Agent, QNet } = require('../assets/snake/engine.js');

const GAMES = Number(process.argv[2] || 400);
const OUT = process.argv[3] || path.join(__dirname, '..', 'assets', 'snake', 'model.js');
const EVAL_EVERY = 25;
const EVAL_GAMES = 200;

function evaluate(net) {
    const agent = new Agent(net);
    let total = 0, best = 0;
    for (let g = 0; g < EVAL_GAMES; g++) {
        const game = new SnakeGame();
        let r;
        do r = game.step(agent.act(game.getState(), { explore: false }).action); while (!r.done);
        total += r.score;
        best = Math.max(best, r.score);
    }
    return { mean: total / EVAL_GAMES, best };
}

function snapshot(net) {
    const copy = new QNet(net.nIn, net.nHidden, net.nOut);
    for (const k of Object.keys(net.params)) copy.params[k] = Float32Array.from(net.params[k]);
    return copy;
}

function write(net, meta) {
    const shapes = {
        w1: [net.nHidden, net.nIn], b1: [net.nHidden],
        w2: [net.nOut, net.nHidden], b2: [net.nOut],
    };
    const model = {};
    for (const k of Object.keys(shapes)) {
        const p = net.params[k];
        model[k] = { shape: shapes[k], data: Buffer.from(p.buffer, p.byteOffset, p.byteLength).toString('base64') };
    }
    model.meta = meta;
    fs.writeFileSync(OUT,
        '// Generated by tools/train_snake.js.\n' +
        '// Linear_QNet(11, 256, 3): float32, row-major, base64-encoded.\n' +
        `window.SNAKE_MODEL = ${JSON.stringify(model, null, 2)};\n`);
}

const agent = new Agent();
const game = new SnakeGame();
let best = null;

while (agent.nGames < GAMES) {
    const state = game.getState();
    const { action } = agent.act(state);
    const { reward, done, score } = game.step(action);
    const t = { state, action, reward, next: game.getState(), done };
    agent.trainShort(t);
    agent.remember(t);

    if (done) {
        game.reset();
        agent.nGames++;
        agent.trainLong();

        if (agent.nGames % EVAL_EVERY === 0) {
            const ev = evaluate(agent.net);
            console.log(`game ${agent.nGames}: last score ${score}, greedy eval mean ${ev.mean.toFixed(2)}, best ${ev.best}`);
            if (!best || ev.mean > best.mean) best = { ...ev, games: agent.nGames, net: snapshot(agent.net) };
        }
    }
}

write(best.net, { trainedGames: best.games, evalGames: EVAL_GAMES, evalMean: +best.mean.toFixed(2), evalBest: best.best });
console.log(`wrote ${OUT} from game ${best.games} (eval mean ${best.mean.toFixed(2)}, best ${best.best})`);
